name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
            - v01
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
            - run: npm test
